name: movies
description: Movies search app with Clean Architecture and TMDB API integration.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  equatable: ^2.0.5
  http: ^1.2.2
  google_fonts: ^6.2.1
  get_it: ^8.0.2
  json_annotation: ^4.12.0
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
